use crate::errors::{ErrorKind, Result};

/// The shape of a note tag icon.
///
/// See [\[MS-ONE\] 2.3.86].
///
/// [\[MS-ONE\] 2.3.86]: https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-one/aa5c7aba-d5e4-4bf8-b265-9100eeb9a7a7
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
#[allow(missing_docs)]
pub enum NoteTagShape {
    NoIcon,
    GreenCheckBox,
    YellowCheckBox,
    BlueCheckBox,
    GreenStarCheckBox,
    YellowStarCheckBox,
    BlueStarCheckBox,
    GreenExclamationCheckBox,
    YellowExclamationCheckBox,
    BlueExclamationCheckBox,
    GreenRightArrowCheckBox,
    YellowRightArrowCheckBox,
    BlueRightArrowCheckBox,
    YellowStar,
    BlueFollowUpFlag,
    QuestionMark,
    BlueRightArrow,
    HighPriority,
    ContactInformation,
    Meeting,
    TimeSensitive,
    LightBulb,
    Pushpin,
    Home,
    CommentBubble,
    SmilingFace,
    AwardRibbon,
    YellowKey,
    BlueCheckBox1,
    BlueCircle1,
    BlueCheckBox2,
    BlueCircle2,
    BlueCheckBox3,
    BlueCircle3,
    BlueEightPointStar,
    BlueCheckMark,
    BlueCircle,
    BlueDownArrow,
    BlueLeftArrow,
    BlueSolidTarget,
    BlueStar,
    BlueSun,
    BlueTarget,
    BlueTriangle,
    BlueUmbrella,
    BlueUpArrow,
    BlueXWithDots,
    BlueX,
    GreenCheckBox1,
    GreenCircle1,
    GreenCheckBox2,
    GreenCircle2,
    GreenCheckBox3,
    GreenCircle3,
    GreenEightPointStar,
    GreenCheckMark,
    GreenCircle,
    GreenDownArrow,
    GreenLeftArrow,
    GreenRightArrow,
    GreenSolidArrow,
    GreenStar,
    GreenSun,
    GreenTarget,
    GreenTriangle,
    GreenUmbrella,
    GreenUpArrow,
    GreenXWithDots,
    GreenX,
    YellowCheckBox1,
    YellowCircle1,
    YellowCheckBox2,
    YellowCircle2,
    YellowCheckBox3,
    YellowCircle3,
    YellowEightPointStar,
    YellowCheckMark,
    YellowCircle,
    YellowDownArrow,
    YellowLeftArrow,
    YellowRightArrow,
    YellowSolidTarget,
    YellowSun,
    YellowTarget,
    YellowTriangle,
    YellowUmbrella,
    YellowUpArrow,
    YellowXWithDots,
    YellowX,
    FollowUpTodayFlag,
    FollowUpTomorrowFlag,
    FollowUpThisWeekFlag,
    FollowUpNextWeekFlag,
    NoFollowUpDateFlag,
    BluePersonCheckBox,
    YellowPersonCheckBox,
    GreenPersonCheckBox,
    BlueFlagCheckBox,
    RedFlagCheckBox,
    GreenFlagCheckBox,
    RedSquare,
    YellowSquare,
    BlueSquare,
    GreenSquare,
    OrangeSquare,
    PinkSquare,
    EMailMessage,
    ClosedEnvelope,
    OpenEnvelope,
    MobilePhone,
    TelephoneWithClock,
    QuestionBalloon,
    PaperClip,
    FrowningFace,
    InstantMessagingContactPerson,
    PersonWithExclamationMark,
    TwoPeople,
    ReminderBell,
    Contact,
    RoseOnAStem,
    CalendarDateWithClock,
    MusicalNote,
    MovieClip,
    QuotationMark,
    Globe,
    HyperlinkGlobe,
    Laptop,
    Plane,
    Car,
    Binoculars,
    PresentationSlide,
    Padlock,
    OpenBook,
    NotebookWithClock,
    BlankPaperWithLines,
    Research,
    Pen,
    DollarSign,
    CoinsWithAWindowBackdrop,
    ScheduledTask,
    LightningBolt,
    Cloud,
    Heart,
    Sunflower,
}

impl NoteTagShape {
    pub(crate) fn parse(value: u16) -> Result<NoteTagShape> {
        match value {
            0 => Ok(NoteTagShape::NoIcon),
            1 => Ok(NoteTagShape::GreenCheckBox),
            2 => Ok(NoteTagShape::YellowCheckBox),
            3 => Ok(NoteTagShape::BlueCheckBox),
            4 => Ok(NoteTagShape::GreenStarCheckBox),
            5 => Ok(NoteTagShape::YellowStarCheckBox),
            6 => Ok(NoteTagShape::BlueStarCheckBox),
            7 => Ok(NoteTagShape::GreenExclamationCheckBox),
            8 => Ok(NoteTagShape::YellowExclamationCheckBox),
            9 => Ok(NoteTagShape::BlueExclamationCheckBox),
            10 => Ok(NoteTagShape::GreenRightArrowCheckBox),
            11 => Ok(NoteTagShape::YellowRightArrowCheckBox),
            12 => Ok(NoteTagShape::BlueRightArrowCheckBox),
            13 => Ok(NoteTagShape::YellowStar),
            14 => Ok(NoteTagShape::BlueFollowUpFlag),
            15 => Ok(NoteTagShape::QuestionMark),
            16 => Ok(NoteTagShape::BlueRightArrow),
            17 => Ok(NoteTagShape::HighPriority),
            18 => Ok(NoteTagShape::ContactInformation),
            19 => Ok(NoteTagShape::Meeting),
            20 => Ok(NoteTagShape::TimeSensitive),
            21 => Ok(NoteTagShape::LightBulb),
            22 => Ok(NoteTagShape::Pushpin),
            23 => Ok(NoteTagShape::Home),
            24 => Ok(NoteTagShape::CommentBubble),
            25 => Ok(NoteTagShape::SmilingFace),
            26 => Ok(NoteTagShape::AwardRibbon),
            27 => Ok(NoteTagShape::YellowKey),
            28 => Ok(NoteTagShape::BlueCheckBox1),
            29 => Ok(NoteTagShape::BlueCircle1),
            30 => Ok(NoteTagShape::BlueCheckBox2),
            31 => Ok(NoteTagShape::BlueCircle2),
            32 => Ok(NoteTagShape::BlueCheckBox3),
            33 => Ok(NoteTagShape::BlueCircle3),
            34 => Ok(NoteTagShape::BlueEightPointStar),
            35 => Ok(NoteTagShape::BlueCheckMark),
            36 => Ok(NoteTagShape::BlueCircle),
            37 => Ok(NoteTagShape::BlueDownArrow),
            38 => Ok(NoteTagShape::BlueLeftArrow),
            39 => Ok(NoteTagShape::BlueSolidTarget),
            40 => Ok(NoteTagShape::BlueStar),
            41 => Ok(NoteTagShape::BlueSun),
            42 => Ok(NoteTagShape::BlueTarget),
            43 => Ok(NoteTagShape::BlueTriangle),
            44 => Ok(NoteTagShape::BlueUmbrella),
            45 => Ok(NoteTagShape::BlueUpArrow),
            46 => Ok(NoteTagShape::BlueXWithDots),
            47 => Ok(NoteTagShape::BlueX),
            48 => Ok(NoteTagShape::GreenCheckBox1),
            49 => Ok(NoteTagShape::GreenCircle1),
            50 => Ok(NoteTagShape::GreenCheckBox2),
            51 => Ok(NoteTagShape::GreenCircle2),
            52 => Ok(NoteTagShape::GreenCheckBox3),
            53 => Ok(NoteTagShape::GreenCircle3),
            54 => Ok(NoteTagShape::GreenEightPointStar),
            55 => Ok(NoteTagShape::GreenCheckMark),
            56 => Ok(NoteTagShape::GreenCircle),
            57 => Ok(NoteTagShape::GreenDownArrow),
            58 => Ok(NoteTagShape::GreenLeftArrow),
            59 => Ok(NoteTagShape::GreenRightArrow),
            60 => Ok(NoteTagShape::GreenSolidArrow),
            61 => Ok(NoteTagShape::GreenStar),
            62 => Ok(NoteTagShape::GreenSun),
            63 => Ok(NoteTagShape::GreenTarget),
            64 => Ok(NoteTagShape::GreenTriangle),
            65 => Ok(NoteTagShape::GreenUmbrella),
            66 => Ok(NoteTagShape::GreenUpArrow),
            67 => Ok(NoteTagShape::GreenXWithDots),
            68 => Ok(NoteTagShape::GreenX),
            69 => Ok(NoteTagShape::YellowCheckBox1),
            70 => Ok(NoteTagShape::YellowCircle1),
            71 => Ok(NoteTagShape::YellowCheckBox2),
            72 => Ok(NoteTagShape::YellowCircle2),
            73 => Ok(NoteTagShape::YellowCheckBox3),
            74 => Ok(NoteTagShape::YellowCircle3),
            75 => Ok(NoteTagShape::YellowEightPointStar),
            76 => Ok(NoteTagShape::YellowCheckMark),
            77 => Ok(NoteTagShape::YellowCircle),
            78 => Ok(NoteTagShape::YellowDownArrow),
            79 => Ok(NoteTagShape::YellowLeftArrow),
            80 => Ok(NoteTagShape::YellowRightArrow),
            81 => Ok(NoteTagShape::YellowSolidTarget),
            82 => Ok(NoteTagShape::YellowSun),
            83 => Ok(NoteTagShape::YellowTarget),
            84 => Ok(NoteTagShape::YellowTriangle),
            85 => Ok(NoteTagShape::YellowUmbrella),
            86 => Ok(NoteTagShape::YellowUpArrow),
            87 => Ok(NoteTagShape::YellowXWithDots),
            88 => Ok(NoteTagShape::YellowX),
            89 => Ok(NoteTagShape::FollowUpTodayFlag),
            90 => Ok(NoteTagShape::FollowUpTomorrowFlag),
            91 => Ok(NoteTagShape::FollowUpThisWeekFlag),
            92 => Ok(NoteTagShape::FollowUpNextWeekFlag),
            93 => Ok(NoteTagShape::NoFollowUpDateFlag),
            94 => Ok(NoteTagShape::BluePersonCheckBox),
            95 => Ok(NoteTagShape::YellowPersonCheckBox),
            96 => Ok(NoteTagShape::GreenPersonCheckBox),
            97 => Ok(NoteTagShape::BlueFlagCheckBox),
            98 => Ok(NoteTagShape::RedFlagCheckBox),
            99 => Ok(NoteTagShape::GreenFlagCheckBox),
            100 => Ok(NoteTagShape::RedSquare),
            101 => Ok(NoteTagShape::YellowSquare),
            102 => Ok(NoteTagShape::BlueSquare),
            103 => Ok(NoteTagShape::GreenSquare),
            104 => Ok(NoteTagShape::OrangeSquare),
            105 => Ok(NoteTagShape::PinkSquare),
            106 => Ok(NoteTagShape::EMailMessage),
            107 => Ok(NoteTagShape::ClosedEnvelope),
            108 => Ok(NoteTagShape::OpenEnvelope),
            109 => Ok(NoteTagShape::MobilePhone),
            110 => Ok(NoteTagShape::TelephoneWithClock),
            111 => Ok(NoteTagShape::QuestionBalloon),
            112 => Ok(NoteTagShape::PaperClip),
            113 => Ok(NoteTagShape::FrowningFace),
            114 => Ok(NoteTagShape::InstantMessagingContactPerson),
            115 => Ok(NoteTagShape::PersonWithExclamationMark),
            116 => Ok(NoteTagShape::TwoPeople),
            117 => Ok(NoteTagShape::ReminderBell),
            118 => Ok(NoteTagShape::Contact),
            119 => Ok(NoteTagShape::RoseOnAStem),
            120 => Ok(NoteTagShape::CalendarDateWithClock),
            121 => Ok(NoteTagShape::MusicalNote),
            122 => Ok(NoteTagShape::MovieClip),
            123 => Ok(NoteTagShape::QuotationMark),
            124 => Ok(NoteTagShape::Globe),
            125 => Ok(NoteTagShape::HyperlinkGlobe),
            126 => Ok(NoteTagShape::Laptop),
            127 => Ok(NoteTagShape::Plane),
            128 => Ok(NoteTagShape::Car),
            129 => Ok(NoteTagShape::Binoculars),
            130 => Ok(NoteTagShape::PresentationSlide),
            131 => Ok(NoteTagShape::Padlock),
            132 => Ok(NoteTagShape::OpenBook),
            133 => Ok(NoteTagShape::NotebookWithClock),
            134 => Ok(NoteTagShape::BlankPaperWithLines),
            135 => Ok(NoteTagShape::Research),
            136 => Ok(NoteTagShape::Pen),
            137 => Ok(NoteTagShape::DollarSign),
            138 => Ok(NoteTagShape::CoinsWithAWindowBackdrop),
            139 => Ok(NoteTagShape::ScheduledTask),
            140 => Ok(NoteTagShape::LightningBolt),
            141 => Ok(NoteTagShape::Cloud),
            142 => Ok(NoteTagShape::Heart),
            143 => Ok(NoteTagShape::Sunflower),
            _ => Err(ErrorKind::MalformedOneNoteFileData(
                format!("invalid note tag shape: {}", value).into(),
            )
            .into()),
        }
    }

    /// Whether the note tag icon is checkable.
    pub fn is_checkable(&self) -> bool {
        matches!(
            self,
            NoteTagShape::GreenCheckBox
                | NoteTagShape::YellowCheckBox
                | NoteTagShape::BlueCheckBox
                | NoteTagShape::GreenStarCheckBox
                | NoteTagShape::YellowStarCheckBox
                | NoteTagShape::BlueStarCheckBox
                | NoteTagShape::GreenExclamationCheckBox
                | NoteTagShape::YellowExclamationCheckBox
                | NoteTagShape::BlueExclamationCheckBox
                | NoteTagShape::GreenRightArrowCheckBox
                | NoteTagShape::YellowRightArrowCheckBox
                | NoteTagShape::BlueRightArrowCheckBox
                | NoteTagShape::BlueCheckBox1
                | NoteTagShape::BlueCheckBox2
                | NoteTagShape::BlueCheckBox3
                | NoteTagShape::GreenCheckBox1
                | NoteTagShape::GreenCheckBox2
                | NoteTagShape::GreenCheckBox3
                | NoteTagShape::YellowCheckBox1
                | NoteTagShape::YellowCheckBox2
                | NoteTagShape::YellowCheckBox3
                | NoteTagShape::FollowUpTodayFlag
                | NoteTagShape::FollowUpTomorrowFlag
                | NoteTagShape::FollowUpThisWeekFlag
                | NoteTagShape::FollowUpNextWeekFlag
                | NoteTagShape::NoFollowUpDateFlag
                | NoteTagShape::BluePersonCheckBox
                | NoteTagShape::YellowPersonCheckBox
                | NoteTagShape::GreenPersonCheckBox
                | NoteTagShape::BlueFlagCheckBox
                | NoteTagShape::RedFlagCheckBox
                | NoteTagShape::GreenFlagCheckBox
        )
    }
}

#[cfg(test)]
mod tests {
    use super::NoteTagShape;

    #[test]
    fn parse_rejects_unknown_shape() {
        assert!(NoteTagShape::parse(u16::MAX).is_err());
    }
}
