#!/bin/sh

# Source-level regression guards for the large-file audit fixes. These checks
# intentionally require no compiler, scanner binary, or generated build tree.

set -eu

root=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)

contains() {
    file=$1
    text=$2
    if ! grep -F -- "$text" "$root/$file" >/dev/null 2>&1; then
        echo "large-file source guard failed: $file does not contain: $text" >&2
        exit 1
    fi
}

not_contains() {
    file=$1
    text=$2
    if grep -F -- "$text" "$root/$file" >/dev/null 2>&1; then
        echo "large-file source guard failed: $file still contains: $text" >&2
        exit 1
    fi
}

if grep -E '^[[:space:]]*uses:[[:space:]]*[^#[:space:]]+@[^0-9a-f]|^[[:space:]]*uses:[[:space:]]*[^#[:space:]]+@[0-9a-f]{1,39}([[:space:]#]|$)' \
    "$root/.github/workflows/cmake.yml" >/dev/null 2>&1; then
    echo 'large-file source guard failed: workflow action is not pinned to an immutable 40-character commit' >&2
    exit 1
fi

contains libclamav/matcher-bm.c 'sizeof(uint64_t), cli_bm_uint64_cmp'
contains libclamav/matcher.h 'CLI_OFF_ANY64'
contains libclamav/matcher.h 'CLI_OFF_NONE64'
contains libclamav/matcher-hash.c 'size >= UINT32_MAX'
contains clamav-milter/clamfi.c 'uint64_t totsz;'
contains clamav-milter/clamfi.c 'unsigned int stream_started;'
contains clamav-milter/clamfi.c 'unsigned int over_limit;'
contains clamav-milter/clamfi.c 'Message exceeds MaxFileSize; refusing a partial scan'
contains clamav-milter/clamfi.c 'clamfi_quota_add(cf->totsz, maxfilesize, len, &next_size)'
not_contains clamav-milter/clamfi.c 'len = (size_t)(maxfilesize - cf->totsz)'
contains clamav-milter/clamfi_quota.c 'configured = CLI_MAX_LARGE_FILESIZE;'
contains clamav-milter/clamfi_quota.c 'requested64 > UINT64_MAX - current'
contains clamav-milter/clamav-milter.c 'clamfi_normalize_maxfilesize'
contains unit_tests/CMakeLists.txt 'add_test(NAME clamav_milter_quota COMMAND check_clamfi_quota)'
contains common/clamdcom.c 'return send_stream_fd_common(sockd, fd, display_filename, clamdopts, true);'
not_contains common/clamdcom.c 'return send_stream_fd_common(sockd, fd, display_filename, clamdopts, false);'
contains libclamav/scanners.c 'ctx->scan_incomplete'
contains libclamav/scanners.c 'status = CL_EMAXSIZE;'
contains libclamav/others.c 'cli_mark_scan_incomplete(ctx, vname);'
contains libclamav/others.c '(ctx->scansize > ctx->engine->maxscansize)'
contains libclamav/scanners.c 'configured_limit_alert_is_visible(ctx)'
contains libclamav/scanners.c 'status = cli_updatelimits(ctx, ctx->fmap->len);'
not_contains libclamav/scanners.c 'if (cli_updatelimits(ctx, ctx->fmap->len) != CL_SUCCESS)'
contains libclamav/scanners.c '*result_out = CL_ETIMEOUT;'
contains libclamav/others.h 'bool scan_timed_out;'
contains libclamav/others.c 'ctx->scan_timed_out = true;'
contains libclamav/scanners.c 'if (ctx->scan_timed_out || result_in == CL_ETIMEOUT)'
contains libclamav/unzip.c 'status = ctx->scan_timed_out ? CL_ETIMEOUT : CL_BREAK;'
contains libclamav/unzip.c 'return ctx->scan_timed_out ? CL_ETIMEOUT : CL_BREAK;'
contains libclamav/unzip.c 'ret != CL_SUCCESS && ret != CL_EPARSE && ret != CL_EFORMAT'
contains libclamav/scanners.c 'emax_reached(ctx);'
contains libclamav/scanners.c 'nested fmap range is outside the containing map'
contains libclamav/scanners.c 'nested fmap could not be read completely while forcing it to disk'
contains libclamav/scanners.c 'while (copied < length)'
not_contains libclamav/scanners.c 'mapdata = fmap_need_off_once_len(map, offset, length'
contains unit_tests/check_clamav.c 'test_nested_fmap_ranges_and_force_to_disk_are_fail_visible'
contains libclamav/matcher.c 'cli_pcre_check_size_limit(ctx, maxfilesize, map->len)'
contains libclamav/matcher.c 'effective_limit > (uint64_t)CLI_MAX_PCRE_CONTIGUOUS_FILESIZE'
contains libclamav/matcher.c 'PCRE signatures require an oversized contiguous subject'
contains libclamav/others.c 'cli_validate_pcre_maxfilesize'
contains libclamav/others.c '*validated = (uint64_t)CLI_MAX_PCRE_CONTIGUOUS_FILESIZE;'
contains libclamav/scanners.c 'legacy file-inspection callback requires an oversized contiguous buffer'
contains libclamav/scanners.c 'image fuzzy hash requires an oversized contiguous buffer'
contains libclamav/scanners.c 'fmap_unneed_off(ctx->fmap, 0, image_size);'
contains libclamav/cache.c 'uint64_t size;'
contains libclamav/cache.c 'static inline int cmp(int64_t *a, uint64_t sa, int64_t *b, uint64_t sb)'
contains libclamav/others.h 'uint64_t size; /* A size of zero means size is unavailable'
contains libclamav/stats_json.c 'snprintf(md5, sizeof(md5), STDu64, sample->size);'
contains unit_tests/check_clamav.c 'test_clean_cache_distinguishes_large_sizes'
contains unit_tests/check_clamav.c 'test_stats_preserves_large_sample_size'
contains unit_tests/check_clamav.c 'test_top_level_maxfilesize_is_fail_visible'
contains unit_tests/check_clamav.c 'test_top_level_maxfilesize_descriptor_is_fail_visible'
contains unit_tests/check_clamav.c 'test_maxscansize_exact_and_crossing_are_fail_visible'
contains unit_tests/check_clamav.c 'test_maxfiles_exact_and_crossing_are_fail_visible'
contains libclamav/mbox.c 'case MAXFILES:'
contains libclamav/mbox.c 'Heuristics.Limits.Exceeded.MaxFiles'
contains unit_tests/check_clamav.c 'test_mbox_nested_maxfiles_is_fail_visible'
contains unit_tests/check_clamav.c 'test_maxrecursion_exact_and_crossing_are_fail_visible'
contains unit_tests/check_clamav.c 'test_configured_limit_result_precedence_and_alert_compatibility'
contains unit_tests/check_clamav.c 'test_callback_abort_is_not_reported_as_timeout'
contains unit_tests/check_clamav.c 'test_timeout_policy_is_fail_visible'
contains unit_tests/check_clamav.c 'test_zip_abort_reason_is_preserved'
contains unit_tests/check_clamav.c 'test_zip_local_index_propagates_callback_abort'
contains libclamav/libclamav.map 'cli_unzip;'
contains libclamav/libclamav.map 'unzip_search_single;'
contains unit_tests/check_matchers.c 'test_pcre_subject_limit_is_fail_visible'
contains libclamav/bytecode.c 'no applicable bytecode registered for hook'
contains libclamav/bytecode_api.c 'cli_bcapi_mark_map_read_error'
contains libclamav/CMakeLists.txt 'Keep the header-only UnRAR interface include path available'
contains unit_tests/check_bytecode.c 'test_bytecode_large_map_hook_gates_only_applicable_bytecode'
contains unit_tests/check_bytecode.c 'test_bytecode_map_read_failure_is_fail_visible'
not_contains common/optparser.c 'Setting this value to zero disables the limit.'
not_contains etc/clamd.conf.sample 'Setting this value to zero disables the limit.'
not_contains docs/man/clamd.conf.5.in 'Setting this value to zero disables the limit.'
not_contains win32/conf_examples/clamd.conf.sample 'Setting this value to zero disables the limit.'
contains libclamav/scanners.c 'VBA decompressed content exceeds the legacy matcher ABI'
contains libclamav/ole2_extract.c 'OLE2 sector chain exceeds the deep-parser ABI'
contains libclamav/scanners.c 'OLE2 VBA project directory could not be parsed'
contains libclamav/libmspack.c 'refusing to scan partial member'
contains libclamav/libmspack.c 'limit_exceeded'
contains libclamav/libmspack.c 'Unlimited still means that the bytes must actually be written.'
contains libclamav/libmspack.c 'max_size = (uint64_t)bytes;'
not_contains libclamav/libmspack.c 'return bytes;'
contains libclamav/ishield.c 'InstallShield MSI member output exceeds configured scan limits'
contains libclamav/ishield.c 'InstallShield CAB output size disagrees with member metadata'
contains libclamav/ishield.c 'InstallShield metadata ended before a complete file record'
contains libclamav/ishield.c 'InstallShield file record ended before its path'
contains libclamav/ishield.c 'Only pin the structure currently being read.'
not_contains libclamav/ishield.c 'fmap_need_off(map, c->hdr, c->hdrsz)'
contains unit_tests/check_clamav.c 'test_ishield_msi_partial_limit_and_decode_failures_are_visible'
contains unit_tests/check_clamav.c 'test_ishield_truncated_metadata_is_fail_visible'
contains libclamav/ishield.c 'InstallShield header metadata is incomplete'
contains libclamav/ishield.c 'InstallShield header has an invalid magic'
contains libclamav/ishield.c '(size_t)(data - fname) > sz - fsize'
contains unit_tests/check_clamav.c 'test_ishield_invalid_embedded_header_is_fail_visible'
contains libclamav/unarj.c 'ARJ member is truncated or outside the input map'
contains libclamav/unarj.c 'ARJ archive ended before its headers were complete'
contains unit_tests/check_clamav.c 'test_arj_truncated_member_is_fail_visible'
contains libclamav/libmspack.c 'CAB archive inspection reached MaxScanSize'
contains libclamav/libmspack.c 'CHM archive inspection reached MaxScanSize'
contains libclamav/libmspack.c 'CL_EOPEN == ret && !tempfile_exists'
contains libclamav/libmspack.c 'CAB extracted member could not be opened'
contains libclamav/libmspack.c 'CHM extracted member could not be opened'
contains unit_tests/check_clamav.c 'test_mspack_scan_limit_is_fail_visible'
contains unit_tests/CMakeLists.txt 'CLAMAV_TEST_MSPACK_CONSTRUCTOR_WRAP'
contains unit_tests/CMakeLists.txt 'wrap=mspack_create_cab_decompressor'
contains unit_tests/CMakeLists.txt 'wrap=mspack_create_chm_decompressor'
contains unit_tests/CMakeLists.txt 'wrap=fmap_new'
contains unit_tests/CMakeLists.txt 'wrap=cli_writen'
contains unit_tests/CMakeLists.txt 'wrap=close'
contains unit_tests/CMakeLists.txt 'CLAMAV_TEST_JS_IO_WRAP'
contains unit_tests/check_clamav.c 'test_mspack_constructor_failures_are_fail_visible'
contains unit_tests/check_clamav.c 'test_normalized_script_map_failure_is_fail_visible'
contains libclamav/elf.c 'ELF header parsing ended before inspection completed'
contains libclamav/elf.c 'ELF program-header parsing ended before inspection completed'
contains libclamav/elf.c 'ELF section-header parsing ended before inspection completed'
contains unit_tests/check_clamav.c 'test_elf_truncated_header_is_fail_visible'
contains libclamav/macho.c 'Mach-O header parsing ended before inspection completed'
contains libclamav/macho.c 'Mach-O parsing ended before inspection completed'
contains libclamav/macho.c 'Mach-O universal-binary parsing ended before inspection completed'
contains unit_tests/check_clamav.c 'test_macho_truncated_header_is_fail_visible'
contains libclamav/udf.c 'UDF generic volume descriptor area is incomplete'
contains libclamav/udf.c 'UDF primary volume descriptor is incomplete'
contains unit_tests/check_clamav.c 'test_udf_truncated_descriptor_area_is_fail_visible'
contains libclamav/hfsplus.c 'HFS+ volume header is incomplete'
contains libclamav/hfsplus.c 'HFS+ inspection ended before completion'
contains unit_tests/check_clamav.c 'test_hfsplus_truncated_header_is_fail_visible'
contains libclammspack/mspack/cabd.c 'report an error even in salvage mode'
contains libclamav/unzip.c 'ZIP_EOCD_MAX_SEARCH_SIZE'
contains libclamav/unzip.c 'ZIP_MAGIC_ZIP64_END'
contains libclamav/unzip.c 'struct zip_central_values {'
contains libclamav/unzip.c 'uint64_t compressed_size;'
contains libclamav/unzip.c 'ALG_DEFLATE64 == method || ALG_BZIP2 == method'
contains libclamav/unzip.c 'strm.state == EXPLODE'
contains libclamav/unzip.c 'output_crc32 != expected_crc32'
contains libclamav/unzip.c 'ZIP encrypted member could not be decrypted with a configured password'
contains libclamav/unzip.c 'ZIP compression method is unsupported by a bounded decoder'
contains libclamav/unzip.c 'if (ctx->scan_incomplete) {'
contains libclamav/unzip.c 'Preserve fallback failures such as timeout and allocation errors.'
contains libclamav/unzip.c 'ret = zip_input_refill(&input, &data, &length);'
contains libclamav/unzip.c 'status = unz_from_fmap('
not_contains libclamav/unzip.c 'compressed_data = fmap_need_off_once('
not_contains libclamav/unzip.c 'fmap_need_ptr_once(ctx->fmap, zip, csize)'
contains libclamav/unzip.c 'ZIP local header could not be mapped for decryption'
contains libclamav/unzip.c 'ZIP member extraction or scanning failed'
contains libclamav/unzip.c 'ZIP archive ended before a complete central header'
contains libclamav/unzip.c 'ZIP local header was truncated'
contains libclamav/scanners.c 'Re-apply the invariant to the final return value.'
contains libclamav/xdp.h 'XDP_DEEP_PARSE_MAX_SIZE'
contains libclamav/xdp.c 'xmlReaderForIO(msxml_read_cb'
contains libclamav/xdp.c 'XDP layer exceeds the 64 MiB libxml2 deep-parser limit'
not_contains libclamav/xdp.c 'xmlReaderForMemory('
not_contains libclamav/xdp.c 'fmap_need_off_once(ctx->fmap, 0, ctx->fmap->len)'
contains libclamav/hwp.h 'HWPML_BASE64_IO_SIZE 16381'
contains libclamav/hwp.c 'cli_hwpml_decode_base64_fd'
contains libclamav/hwp.c 'HWPML layer exceeds the 64 MiB libxml2 deep-parser limit'
contains libclamav/hwp.c 'HWPOLE2 payload exceeds its 32-bit size field'
not_contains libclamav/hwp.c 'fmap_need_off_once(input, 0, input->len)'
contains libclamav/gif.c 'static cl_error_t gif_parse_error'
contains libclamav/gif.c 'Heuristics.Broken.Media.GIF.TruncatedGraphicControlExtension'
contains libclamav/gif.c 'Heuristics.Broken.Media.GIF.MissingTrailer'
contains unit_tests/check_clamav.c 'test_gif_truncated_blocks_are_fail_visible'
contains libclamav/png.c 'static cl_error_t png_parse_error'
contains libclamav/png.c 'Heuristics.Broken.Media.PNG.MissingIEND'
contains libclamav/png.c 'Heuristics.Broken.Media.PNG.InvalidIENDLength'
contains unit_tests/check_clamav.c 'test_png_truncated_chunks_are_fail_visible'
contains libclamav/tiff.c 'static cl_error_t tiff_parse_error'
contains libclamav/tiff.c 'Heuristics.Broken.Media.TIFF.EOFReadingIFDEntry'
contains unit_tests/check_clamav.c 'test_tiff_truncated_structures_are_fail_visible'
contains libclamav/special.c 'RIFF inspection exceeded the nested-list limit'
contains libclamav/special.c 'RIFF chunk data was truncated'
contains unit_tests/check_clamav.c 'test_riff_truncated_chunk_is_fail_visible'
contains libclamav/jpeg.c 'static cl_error_t jpeg_parse_error'
contains libclamav/jpeg.c 'Heuristics.Broken.Media.JPEG.TruncatedHeader'
contains unit_tests/check_clamav.c 'test_jpeg_truncated_structures_are_fail_visible'
contains libclamav/htmlnorm.h 'bool read_error'
contains libclamav/htmlnorm.c 'HTML normalization could not read the complete input map'
contains libclamav/htmlnorm.c 'HTML normalized output could not be written completely'
contains libclamav/scanners.c 'A failed HTML normalization must not be scanned as a complete layer.'
contains unit_tests/check_htmlnorm.c 'test_htmlnorm_mapped_read_failure_is_fail_visible'
contains libclamav/textnorm.h 'bool read_error'
contains libclamav/textnorm.c 'state->read_error = true'
contains libclamav/scanners.c 'Script normalization could not read the complete input map'
contains libclamav/scanners.c 'Script normalized output could not be written completely'
contains libclamav/scanners.c 'Script normalization did not consume the complete input map'
contains unit_tests/check_clamav.c 'test_text_normalize_map_read_failure_is_fail_visible'
contains libclamav/pe_icons.c 'static int icon_parse_error'
contains libclamav/pe_icons.c 'PE icon scan reached the configured icon limit'
contains unit_tests/check_clamav.c 'test_pe_icon_truncated_resource_is_fail_visible'
contains libclamav/pdf.c 'PDF trailer is missing the %%EOF marker'
contains libclamav/pdf.c 'PDF trailer xref is invalid'
contains libclamav/pdfdecode.c 'PDF stream decoding did not complete'
contains libclamav/pdfdecode.c 'Flate stream has no compressed payload'
contains libclamav/pdfdecode.c 'LZW stream has no compressed payload'
contains unit_tests/check_clamav.c 'test_pdf_truncated_trailer_is_fail_visible'
contains unit_tests/check_clamav.c 'test_pdf_decode_error_is_fail_visible'
contains unit_tests/check_clamav.c 'test_pdf_empty_flate_stream_is_fail_visible'
contains unit_tests/check_bytecode.c 'missing bytecode fixture'
contains libclamav/hwp.c 'MSXML_FLAG_JSON | MSXML_FLAG_FAIL_INCOMPLETE'
contains unit_tests/check_clamav.c 'test_hwpml_truncated_document_is_fail_visible'
contains libclamav/pdf.h 'PDF_DEEP_PARSE_MAX_SIZE'
contains libclamav/pdf.c 'PDF layer exceeds the 64 MiB legacy deep-parser limit'
contains libclamav/pdf.c 'fmap_readn(map, pdf_input + copied'
not_contains libclamav/pdf.c 'fmap_need_off(map, offset, size)'
contains libclamav/pdfdecode.c 'PDF raw stream exceeded configured scan limits'
contains libclamav/pdfdecode.c 'PDF decoded stream exceeded configured scan limits'
contains libclamav/pdfdecode.c 'PDF decoded stream could not be written completely'
contains libclamav/pdf.c 'PDF extracted object exceeded configured scan limits'
contains libclamav/pdf.c 'PDF extracted object could not be written completely'
contains unit_tests/check_clamav.c 'test_large_document_parser_caps_are_fail_visible'
contains unit_tests/check_clamav.c 'test_cl_fmap_set_hash_accepts_full_hash'
contains unit_tests/check_clamav.c 'test_html_normalize_default_cap_is_fail_visible'
contains unit_tests/check_clamav.c 'test_metadata_hash_read_failure_is_fail_visible'
contains unit_tests/check_jsnorm.c 'test_js_output_open_failure_is_visible'
contains unit_tests/check_jsnorm.c 'test_js_output_write_and_close_failures_are_visible'
contains CMakeLists.txt 'set(LIBCLAMAV_CURRENT  14)'
contains CMakeLists.txt 'set(LIBCLAMAV_AGE      0)'
contains libclamav/fmap.c 'end_offset = map->len;'
contains libclamav/scanners.c 'RAR input could not be staged completely'
contains libclamav/jsparse/js-norm.h 'cl_error_t cli_js_output'
contains libclamav/htmlnorm.c 'JavaScript normalization output could not be completed'
contains libclamav/bytecode_api.c 'JavaScript normalization output could not be completed'
contains libclamav/scanners.c 'Script normalized output could not be mapped for scanning'
contains libclamav/libmspack.c 'CAB decompressor could not be constructed'
contains unit_tests/check_clamav.c 'cli_mscab_header_check(&ctx, 0, &cab_size)'
contains libclamav/libmspack.c 'CHM decompressor could not be constructed'
contains common/optparser.c 'parse_max_scantime'
contains unit_tests/check_clamd.c 'test_maxscantime_parser_rejects_narrowing'
contains unit_tests/check_clamd.c 'test_maxscantime_cli_boundaries'
contains unit_tests/check_clamav.c 'test_macho_section_alignment_exponent_is_fail_visible'
contains unit_tests/check_clamav.c 'test_hwp3_truncated_raw_deflate_is_fail_visible'
contains unit_tests/check_clamav.c 'test_onenote_dispatch_honors_document_dconf'
contains unit_tests/check_clamav.c 'test_pdf_truncated_flate_after_prefix_is_fail_visible'
contains unit_tests/check_clamav.c 'test_pdf_truncated_lzw_after_prefix_is_fail_visible'
contains unit_tests/check_clamav.c 'test_zip_truncated_entry_paths_are_fail_visible'
contains unit_tests/check_clamav.c 'test_xz_truncated_stream_is_fail_visible'
contains tools/largefile_runtime_gate.sh 'runtime-components'
contains tools/largefile_runtime_evidence_check.sh 'runtime component artifacts are missing'
contains tools/largefile_poc.sh 'peak_tmp_bytes'
contains tools/largefile_service_qualification.sh 'service_qualification=pass'
contains tools/largefile_service_qualification.sh 'MILTER_EXACT_EDGE=1'
contains tools/largefile_service_qualification.sh 'milter_exact_edge=pass'
contains tools/largefile_service_qualification.sh 'clamd_multiworker_count=4'
contains tools/largefile_service_qualification.sh 'clamd_multiworker=pass'
contains tools/largefile_service_qualification.sh 'cold_cache_control=pass'
contains .github/workflows/cmake.yml "CLAMAV_MAX_SCAN_TIME_MS: '900000'"
contains .github/workflows/cmake.yml 'Mandatory service and workload qualification'
contains .github/workflows/cmake.yml 'clamav-largefile-service/SHA256SUMS'
contains .github/workflows/cmake.yml 'production_database:'
contains .github/workflows/cmake.yml 'expansion_fixture:'
contains unit_tests/check_clamav.c 'test_pdf_stream_limit_is_fail_visible'
contains unit_tests/check_clamav.c 'test_pdf_extracted_object_limit_is_fail_visible'
contains unit_tests/check_clamav.c 'test_hwpml_base64_decoder_is_bounded_and_fail_visible'
contains libclamav/hwp.c 'Heuristics.Limits.Exceeded.MaxRecursion", CL_EMAXREC'
contains libclamav/ole2_extract.c 'Heuristics.Limits.Exceeded.MaxScanSize", CL_EMAXSIZE'
contains libclamav/ole2_extract.c 'fixed recursion limit reached (max: 100)'
contains libclamav/ole2_extract.c 'fixed file limit reached (max: 100000)'
contains libclamav/ole2_extract.c 'OLE2 stream could not be materialized completely'
contains libclamav/ole2_extract.c 'OLE2 encrypted stream could not be materialized completely'
contains libclamav/ole2_extract.c 'OLE2 temporary directory could not be created'
contains libclamav/ole2_extract.c 'OLE2 property tree index is outside the input map'
contains libclamav/ole2_extract.c 'OLE2 property sector chain could not be read'
contains libclamav/ole2_extract.c 'OLE2 property tree could not be read'
contains libclamav/ole2_extract.c 'OLE2 property tree contains an invalid entry type'
contains libclamav/ole2_extract.c 'OLE2 property tree contains an invalid name length'
contains libclamav/ole2_extract.c 'OLE2 property tree contains a loop'
contains libclamav/ole2_extract.c 'OLE2 property tree visit tracking failed'
contains libclamav/ole2_extract.c 'OLE2 property tree contains an illegal Root Entry'
contains libclamav/ole2_extract.c 'OLE2 property tree contains an unknown entry type'
contains libclamav/ole2_extract.c 'OLE2 XLM/image stream could not be scanned completely'
contains libclamav/ole2_extract.c 'OLE2 property enumeration failed'
contains libclamav/ole2_extract.c 'OLE2 embedded stream scan failed'
contains libclamav/ole2_extract.c 'OLE2 embedded encrypted stream scan failed'
contains libclamav/msexpand.c 'MSEXPAND input ended before the declared output was produced'
contains libclamav/msexpand.c 'if ((status = cli_checklimits("MSEXPAND", ctx, fsize, 0, 0)) != CL_CLEAN)'
contains unit_tests/check_clamav.c 'test_legacy_parser_limit_returns_are_fail_visible'
contains unit_tests/check_clamav.c 'test_msexpand_truncated_output_is_fail_visible'
contains libclamav/tnef.c 'TNEF attribute header was truncated'
contains libclamav/tnef.c 'TNEF header was truncated'
contains unit_tests/check_clamav.c 'test_tnef_truncated_header_is_fail_visible'
contains unit_tests/check_clamav.c 'test_tnef_short_header_is_fail_visible'
contains libclamav/uuencode.c 'return saw_end ? 1 : -1;'
contains libclamav/scanners.c 'UUencoded attachment was not terminated or decoded completely'
contains unit_tests/check_clamav.c 'test_uuencode_truncated_attachment_is_fail_visible'
contains libclamav/mbox.c 'UUencoded attachment in mail was not terminated or decoded completely'
contains libclamav/mbox.c 'BinHex mail attachment could not be materialized'
contains libclamav/message.c 'Set the scan context before the fast-copy path can return'
contains libclamav/sis.c 'SIS 9.x contents field was truncated or invalid'
contains libclamav/sis.c 'SIS 9.x content stream was incomplete'
contains libclamav/untar.c 'TAR entry ended before its declared content length'
contains libclamav/cpio.c 'CPIO archive ended before a complete trailer'
contains libclamav/iso9660.c 'ISO directory block could not be read'
contains libclamav/iso9660.c 'ISO interleaved file layout is unsupported'
contains libclamav/iso9660.c 'ISO multi-extent file layout is unsupported'
contains libclamav/7z_iface.c '7-Zip archive header could not be parsed completely'
contains libclamav/xar.c 'XAR header is incomplete'
contains libclamav/xar.c 'XAR header has invalid magic'
contains libclamav/xar.c 'XAR TOC XML reader failed before file entries were inspected'
contains libclamav/xar.c 'XML reader failed while reading TOC data values'
contains libclamav/xar.c 'XAR inspection ended before completion'
contains libclamav/scanners.c 'GZip stream ended before decompression completed'
contains libclamav/scanners.c 'GZip legacy stream did not reach a complete decoder state'
contains libclamav/scanners.c 'GZip legacy decoder did not close cleanly'
contains libclamav/scanners.c 'Bzip stream ended before decompression completed'
contains libclamav/scanners.c 'XZ decompressed output exceeds configured scan limits'
contains libclamav/scanners.c 'refusing to scan partial output at'
contains libclamav/swf.c 'SWF zlib stream ended before decompression completed'
contains libclamav/swf.c 'SWF LZMA stream ended before decompression completed'
contains libclamav/swf.c 'SWF file header was truncated'
contains libclamav/swf.c 'SWF uncompressed file was shorter than its declared size'
contains libclamav/swf.c 'SWF frame metadata was truncated'
contains libclamav/msxml_parser.c 'MSXML document ended before XML content was fully inspected'
contains libclamav/msxml_parser.h 'MSXML_FLAG_FAIL_INCOMPLETE'
contains unit_tests/check_clamav.c 'test_msxml_truncated_document_is_fail_visible'
contains libclamav/rtf.c 'RTF document ended before parsing completed'
contains libclamav/rtf.c 'RTF embedded object ended before its payload was complete'
contains unit_tests/check_clamav.c 'test_rtf_truncated_document_is_fail_visible'
contains libclamav/scanners.c 'RAR file header ended before archive inspection completed'
contains libclamav/scanners.c 'RAR encrypted member contents were not inspected'
contains libclamav/scanners.c 'RAR extracted member could not be opened'
contains unit_tests/check_clamav.c 'test_rar_truncated_header_is_fail_visible'
contains libclamunrar/dll.cpp 'Data->Arc.GetHeaderType() != HEAD_ENDARC'
contains unit_tests/check_clamav.c 'test_rar_nested_stage_read_failure_is_publicly_fail_visible'
contains libclamav/scanners.c 'ARJ member extraction was incomplete'
contains unit_tests/check_clamav.c 'test_arj_truncated_member_extraction_is_fail_visible'
contains libclamav/scanners.c 'ARJ member exceeded configured scan limits'
contains unit_tests/check_clamav.c 'test_arj_member_limit_is_fail_visible'
contains libclamav/ole2_extract.c 'OLE2: embedded file exceeds configured scan limits'
contains unit_tests/check_clamav.c 'test_ole2_member_limit_is_fail_visible'
contains libclamav/spin.c 'Heuristics.Limits.Exceeded.MaxFileSize'
contains libclamav/spin.c 'cli_pespin_check_limits'
contains libclamav/pe.c 'cli_scanpe: PESpin: Size exceeded'
contains unit_tests/check_clamav.c 'test_pespin_limit_accounting_is_fail_visible'
contains unit_tests/check_clamav.c 'test_mbox_truncated_uuencode_is_fail_visible'
contains unit_tests/check_clamav.c 'test_mbox_truncated_binhex_is_fail_visible'
contains unit_tests/check_clamav.c 'test_sis_truncated_contents_is_fail_visible'
contains unit_tests/check_clamav.c 'test_sis_member_limit_is_fail_visible'
contains unit_tests/check_clamav.c 'test_tar_truncated_header_is_fail_visible'
contains unit_tests/check_clamav.c 'test_cpio_truncated_header_is_fail_visible'
contains unit_tests/check_clamav.c 'test_iso_truncated_directory_is_fail_visible'
contains unit_tests/check_clamav.c 'test_iso_unsupported_extent_layouts_are_fail_visible'
contains unit_tests/check_clamav.c 'test_xar_truncated_header_is_fail_visible'
contains unit_tests/check_clamav.c 'test_xar_xml_reader_error_is_fail_visible'
contains libclamav/mbr.c 'MBR inspection ended before completion'
contains libclamav/apm.c 'APM inspection ended before completion'
contains libclamav/gpt.c 'GPT inspection ended before completion'
contains libclamav/hwp.c 'HWP3 inspection ended before completion'
contains libclamav/hwp.c 'HWP3 password-protected content cannot be parsed'
contains unit_tests/check_clamav.c 'test_partition_parser_errors_are_fail_visible'
contains unit_tests/check_clamav.c 'test_hwp3_parser_errors_are_fail_visible'
contains unit_tests/check_clamav.c 'test_hwp3_password_protection_is_fail_visible'
contains unit_tests/check_clamav.c 'test_7z_truncated_header_is_fail_visible'
contains unit_tests/check_clamav.c 'test_gzip_bzip_truncated_streams_are_fail_visible'
contains unit_tests/check_clamav.c 'test_xz_limit_is_fail_visible'
contains unit_tests/check_clamav.c 'test_swf_zlib_truncated_stream_is_fail_visible'
contains unit_tests/check_clamav.c 'test_swf_truncated_uncompressed_header_is_fail_visible'
contains unit_tests/check_clamav.c 'test_swf_truncated_frame_metadata_is_fail_visible'
contains unit_tests/check_clamav.c 'test_zip_truncated_entry_paths_are_fail_visible'
contains libclamav/binhex.c 'BinHex stream ended before its header was decoded'
contains unit_tests/check_clamav.c 'test_binhex_truncated_header_is_fail_visible'
contains libclamav/ole2_extract.c 'ret = ole2_walk_property_tree(&hdr, dirname, 0, handler_writefile'
contains libclamav/ole2_extract.c 'MSO stream output exceeded configured scan limits'
contains libclamav/ole2_extract.c 'MSO stream did not reach a complete zlib terminal state'
contains libclamav/ole2_extract.c 'OLE2 header was truncated'
contains unit_tests/check_clamav.c 'test_ole2_truncated_property_tree_is_fail_visible'
contains unit_tests/check_clamav.c 'test_ole2_vba_materialization_failure_is_fail_visible'
contains unit_tests/check_clamav.c 'test_mbox_materialization_limit_is_fail_visible'
contains unit_tests/check_clamav.c 'test_mbox_materialization_limit_without_alert_is_fail_visible'
contains unit_tests/check_clamav.c 'test_single_message_materialization_limit_is_fail_visible'
contains unit_tests/check_clamav.c 'test_single_message_materialization_limit_without_alert_is_fail_visible'
contains libclamav/mbox.c 'rc = FAIL;'
contains libclamav/dmg.h 'DMG_XML_PARSE_MAX_SIZE'
contains libclamav/dmg.c 'xmlReaderForIO(dmg_xml_read_cb'
contains libclamav/dmg.c 'DMG deflate stripe output does not match its declared sector count'
contains libclamav/dmg.c 'DMG bzip2 stripe did not reach stream completion'
contains libclamav/dmg.c 'DMG contains invalid or unsupported non-empty stripe metadata'
contains libclamav/dmg.c 'hdr.dataForkOffset, hdr.dataForkLength'
contains libclamav/dmg.c 'mish_set->mish->dataOffset + blocklist[i].dataOffset'
contains libclamav/dmg.c 'DMG stripe geometry has a gap, overlap, or out-of-range sector span'
contains libclamav/dmg.c 'multi-segment DMG images require data from another file'
contains libclamav/dmg.c 'DMG XML parsing reached the configured time limit'
contains libclamav/dmg.c 'DMG trailer block has invalid magic'
contains libclamav/dmg.c 'DMG trailer block is incomplete'
contains libclamav/dmg.c 'contains invalid Base64 syntax'
contains libclamav/dmg.c 'has no terminal END stripe'
not_contains libclamav/dmg.c 'xmlReaderForMemory('
not_contains libclamav/dmg.c 'strm.next_in = (void *)fmap_need_off_once(ctx->fmap, off, len)'
contains unit_tests/check_clamav.c 'test_dmg_malformed_metadata_is_fail_visible'
contains unit_tests/check_clamav.c 'test_dmg_invalid_trailer_is_fail_visible'
contains unit_tests/check_clamav.c 'test_dmg_xml_limit_is_fail_visible_without_materializing_payload'
contains unit_tests/check_clamav.c 'test_dmg_strict_base64_and_terminal_end_validation'
contains libclamav/asn1.h 'size_t offset;'
contains libclamav/asn1.h 'size_t size;'
contains libclamav/asn1.c 'cli_hash_mapped_regions('
contains libclamav/asn1.c 'CLI_AUTHENTICODE_HASH_CHUNK_SIZE'
contains libclamav/asn1.c 'Authenticode hash region could not be read completely'
not_contains libclamav/asn1.c 'fmap_need_off_once(map, regions[i].offset, regions[i].size)'
contains libclamav/pe.c 'ret = cli_hash_mapped_regions(map, hashctx, regions, nregions, ctx);'
contains libclamav/pe.c 'status = cli_hash_mapped_regions(ctx->fmap, hash_ctx, &region, 1, ctx);'
not_contains libclamav/pe.c 's->rsz > CLI_MAX_ALLOCATION'
contains libclamav/execs.h 'size_t overlay_start;'
contains libclamav/execs.h 'size_t overlay_size;'
contains libclamav/pe.c 'PE bytecode overlay metadata requires 32-bit coordinates'
contains libclamav/pe.c 'cli_pe_calculate_overlay_range('
contains unit_tests/check_clamav.c 'test_authenticode_hash_regions_are_native_and_bounded'
contains unit_tests/check_clamav.c 'test_authenticode_hash_failure_is_fail_visible'
contains unit_tests/check_clamav.c 'test_pe_overlay_range_preserves_native_size'
contains libclamav/pe.c 'PE header parsing ended with a malformed or truncated header'
contains libclamav/pe.c 'PE header parsing failed before PE-specific inspection completed'
contains libclamav/pe.c 'PE unpacked content exceeded configured scan limits'
contains unit_tests/check_clamav.c 'test_pe_truncated_header_is_fail_visible'
contains unit_tests/check_clamav.c 'test_pe_unpack_limit_is_fail_visible'
contains libclamav/udf.c 'UDF_COPY_CHUNK_SIZE'
contains libclamav/udf.c 'UDF file extent exceeds configured scan limits'
not_contains libclamav/udf.c 'fmap_need_off(ctx->fmap, offset, length)'
contains libclamav/gpt.c 'gpt_crc32_fmap'
contains libclamav/gpt.c 'GPT partition count exceeds the configured inspection limit'
not_contains libclamav/gpt.c 'fmap_need_off_once(ctx->fmap, ptable_start, ptable_len)'
contains libclamav/autoit.c 'bb == 0 || bb > UNP.cur_output'
contains libclamav/autoit.c 'chars > UINT32_MAX / 2'
contains libclamav/autoit.c 'AutoIt EA06 script decompilation was incomplete'
not_contains libclamav/autoit.c 'return CL_VIRUS;'
contains libclamav/xar.c 'XAR_TOC_DEEP_PARSE_MAX_SIZE'
contains libclamav/xar.c 'XAR gzip member ended before the decoder reached stream end'
not_contains libclamav/xar.c 'writelen = MIN((size_t)(ctx->engine->maxfilesize), writelen)'
contains libclamav/nsis/nulsft.c 'NSIS_CONTIGUOUS_INPUT_MAX'
contains libclamav/nsis/nulsft.c 'NSIS decompression produced only a partial member'
not_contains libclamav/nsis/nulsft.c 'ret = nsist.solid ? CL_BREAK : CL_SUCCESS'
contains libclamav/egg.c 'compressedDataOffset'
contains libclamav/egg.c 'block exceeds the bounded contiguous decoder limit'
contains libclamav/scanners.c 'EGG member extraction failed before content scanning'
contains libclamav/blob.c 'overlap adjacent windows'
contains libclamav/blob.c 'deferring early scan to preserve multipart/logical matcher state'
contains libclamav/matcher-byte-comp.c 'buffer_offset'
contains libclamav_rust/src/sys.rs 'filesize_range: *mut u64'
contains libclamav_rust/build.rs '.layout_tests(true)'
contains libclamav_rust/src/fmap.rs 'whole_input_rejects_oversized_maps_before_residency_request'
contains libclamav_rust/src/fmap.rs 'need_failure_is_reported_as_a_bounded_error'
contains libclamav_rust/src/scanners.rs 'sys::emax_reached(ctx);'
contains libclamav_rust/build.rs '"emax_reached",'
contains tools/largefile_poc.sh 'row_signature='
contains tools/largefile_poc.sh 'unsigned="signature $row_signature.UNOFFICIAL matched at "'
contains tools/largefile_poc_fail_closed_test.sh 'positive scanner stub'
contains tools/largefile_runtime_gate.sh 'runtime-gate requires Linux x86-64'
contains tools/largefile_runtime_gate.sh 'CLAMAV_SANITIZER_CLAMSCAN'
contains tools/largefile_runtime_gate.sh 'policy_32g_plus_one'
contains tools/largefile_runtime_gate.sh 'cancellation=pass'
contains tools/largefile_runtime_gate.sh 'CLAMAV_CONCURRENCY_FILE:-32g-edge.bin'
contains tools/largefile_runtime_gate.sh 'CLAMAV_MIN_AVAILABLE_KB'
contains tools/largefile_runtime_gate.sh 'CLAMAV_MAX_SCAN_TIME_MS'
contains tools/largefile_runtime_gate.sh 'CLAMAV_SANITIZER_MAX_SCAN_TIME_MS'
contains tools/largefile_runtime_gate.sh '4294967295'
contains tools/largefile_poc.sh '4294967295'
contains tools/largefile_runtime_gate.sh 'CLAMAV_CVD_CERTS_DIR'
contains tools/largefile_runtime_gate.sh 'host preflight failed'
contains tools/largefile_runtime_gate.sh 'runtime_gate=pass'
contains tools/largefile_host_preflight.sh 'memory_total_kb='
contains tools/largefile_host_preflight.sh 'cgroup_memory_limit_bytes='
contains tools/largefile_host_preflight.sh 'effective_memory_available_kb='
contains .github/workflows/cmake.yml "CLAMAV_MIN_AVAILABLE_KB: '50331648'"
contains .github/workflows/cmake.yml "CLAMAV_MAX_TEMP_BYTES: '67108864'"
contains .github/workflows/cmake.yml 'CLAMAV_MAX_SCAN_TIME_MS'
contains .github/workflows/cmake.yml "CLAMAV_SANITIZER_MAX_SCAN_TIME_MS: '3600000'"
contains .github/workflows/cmake.yml "CLAMAV_SANITIZER_RUST_SUITE: 'pass'"
contains .github/workflows/cmake.yml 'Install Rust sanitizer toolchain'
contains .github/workflows/cmake.yml 'RUSTUP_TOOLCHAIN: nightly'
contains .github/workflows/cmake.yml 'RUSTFLAGS: -Zsanitizer=address'
contains .github/workflows/cmake.yml 'CLAMAV_SANITIZER_TOOLCHAIN: nightly'
contains .github/workflows/cmake.yml "CLAMAV_SANITIZER_RUSTFLAGS: '-Zsanitizer=address'"
contains tools/largefile_runtime_gate.sh 'sanitizer_rust_suite='
contains tools/largefile_runtime_gate.sh 'rust-sanitizer-symbols.txt'
contains tools/largefile_runtime_evidence_check.sh 'sanitizer evidence does not prove Rust instrumentation'
contains tools/largefile_runtime_evidence_check.sh 'sanitizer evidence does not prove the supported Rust CTest suite passed'
contains .github/workflows/cmake.yml 'CLAMAV_CVD_CERTS_DIR'
contains .github/workflows/cmake.yml 'build-largefile/clamscan/clamscan'
contains .github/workflows/cmake.yml 'build-sanitizer/clamscan/clamscan'
contains .github/workflows/cmake.yml 'clamav-largefile-64gb'
contains .github/workflows/cmake.yml 'actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be'
contains CMakeLists.txt 'CLAMAV_SOURCE_COMMIT'
contains CMakeLists.txt 'CLAMAV_SOURCE_MANIFEST_SHA256'
contains CMakeLists.txt '-C "${CMAKE_CURRENT_SOURCE_DIR}" rev-parse --verify HEAD'
contains libclamav/fmap.c 'lseek failed for staged fmap'
contains tools/largefile_source_manifest.sh 'Git-less'
contains tools/largefile_runtime_gate.sh 'source-manifest.txt'
contains tools/largefile_runtime_evidence_check.sh 'source_manifest_sha256='
contains tools/largefile_runtime_gate.sh 'source_commit='
contains tools/largefile_runtime_gate.sh 'source_tree='
contains tools/largefile_runtime_gate.sh 'compile_commands.json'
contains tools/largefile_runtime_evidence_check.sh 'compile-commands hash does not match build identity'
contains tools/largefile_runtime_gate.sh 'SHA256SUMS'
contains tools/largefile_runtime_gate.sh 'repository-tree.txt'
contains tools/largefile_runtime_gate.sh 'repository-index.txt'
contains tools/largefile_runtime_evidence_check.sh 'repository metadata manifests do not contain every tracked file'
contains tools/largefile_runtime_evidence_check.sh 'sha256sum -c'
contains CMakeLists.txt 'does not support native Windows'
contains tools/largefile_runtime_evidence_check.sh 'large-file runtime evidence verified'
contains tools/largefile_runtime_evidence_check.sh 'POC results do not contain eleven passing exact-size/offset rows'
contains tools/largefile_runtime_evidence_check.sh 'runtime gate does not have an explicit pass marker'
contains tools/largefile_runtime_evidence_check.sh 'fixed release per-file scan deadline'
contains tools/largefile_runtime_evidence_check.sh 'fixed sanitizer-only scan deadline'
contains tools/largefile_runtime_evidence_check.sh 'fixed temporary-space budget'
contains tools/largefile_boundary_corpus.sh 'make_marker 4g-minus-two 4294967294'
contains tools/largefile_runtime_evidence_check.sh '32g-edge.bin'
contains tools/largefile_runtime_evidence_check.sh 'host preflight does not record total memory'
contains tools/largefile_runtime_evidence_check.sh '$10 != off[row]'
contains tools/largefile_runtime_evidence_check.sh 'worker-$worker.rss-kb'
contains tools/largefile_runtime_evidence_check_test.sh 'evidence checker accepted a wrong numeric engine offset'
contains tools/largefile_runtime_evidence_check_test.sh 'evidence checker accepted an RSS record that disagrees with the worker log'
contains common/optparser.c 'cannot exceed 32G in this build'
contains CMakeLists.txt 'CLAMAV_LARGE_FILE_SUPPORT 1'

if grep -F 'Technical design limitations prevent ClamAV from scanning files greater than' "$root/etc/clamd.conf.sample" >/dev/null 2>&1; then
    echo 'large-file source guard failed: stale clamd.conf size limit documentation' >&2
    exit 1
fi

awk -F '\t' '
    NR == 1 { next }
    $2 ~ /^\.\// { exit 1 }
    seen[$0]++
    END {
        for (row in seen)
            if (seen[row] != 1)
                exit 2
    }
' "$root/docs/largefile-inventory.tsv"

echo 'large-file source guards passed'
